"""fix: relationship for account and transaction for 2 foreign keys

Revision ID: a32ec2bffc0e
Revises: 85e37bf273d6
Create Date: 2025-04-03 23:42:01.095575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32ec2bffc0e'
down_revision = '85e37bf273d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('to_account_id', sa.Integer(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.drop_constraint('transactions_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'accounts', ['from_account_id'], ['id'])
        batch_op.create_foreign_key(None, 'accounts', ['to_account_id'], ['id'])
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_account_id_fkey', 'accounts', ['account_id'], ['id'])
        batch_op.alter_column('amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('to_account_id')
        batch_op.drop_column('from_account_id')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
