SQLALCHEMY_DATABASE_URI = "postgresql://postgres.ntkmyddmxvzhnsbvcwlk:Erk62CsBHInWx52s@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres"

JWT_SECRET_KEY = "revou-milestone-3"

JWT_ACCESS_TOKEN_EXPIRES = 180

# No expired user token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0MzkyNjc3MCwianRpIjoiMDk3MzUyZWQtMWIzMy00MjEzLTkzMTctMWI3MjY0NGM4Y2FhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3NDM5MjY3NzAsImNzcmYiOiJlNjA3MzFmYS0wZDk1LTQ0YWItYjUxMS1hNjQyNWJkNTFmMjQifQ._HtTn6o2qrVnPLwz1WP-4b2mdNXqBQWjUWUqL95nfq8

# No expired admin token "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NDIwNjAxNiwianRpIjoiNjUzYWRjYWQtMjczZC00YjRlLWE3MjUtYTQ0OTRhMzRmOGQyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjI4IiwibmJmIjoxNzQ0MjA2MDE2LCJjc3JmIjoiYzQ0NDM1MjAtZDg1Mi00NWI2LTk4OGYtNjE1N2M3NzU0ZGMwIn0.0o0MBWOz6PFPp1j2Mxy61ViYWwXMP_Ow9VPjgiblIxE"



# db
# REVOU-milestone-3
# Erk62CsBHInWx52s
# https://ntkmyddmxvzhnsbvcwlk.supabase.co
